In [1]:
import pandas as pd
import numpy as np

### 1. Data collection

In [2]:
Data_set=pd.read_csv("Social_Network_Ads.csv")
Data_set

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
Data=pd.get_dummies(Data_set,drop_first=True)
Data

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
Data=Data.drop("User ID",axis=1)
Data

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
Data["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

### 2.Split the input and output

In [6]:
independent=Data[["Age","EstimatedSalary","Gender_Male"]]
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [7]:
dependent=Data[["Purchased"]]
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

### 3.Split the train and test data

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
x_test

Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
216   49            65000            1
259   45           131000            0
49    31            89000            0
238   46            82000            0
343   47            51000            0

[120 rows x 3 columns]

### 4.Model crearion

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

C:\Users\smani\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [27]:
x_test

array([[3.00000000e+01, 8.70000000e+04, 1.00000000e+00],
       [3.80000000e+01, 5.00000000e+04, 3.17206578e-17],
       [3.50000000e+01, 7.50000000e+04, 1.00000000e+00],
       [3.00000000e+01, 7.90000000e+04, 3.17206578e-17],
       [3.50000000e+01, 5.00000000e+04, 3.17206578e-17],
       [2.70000000e+01, 2.00000000e+04, 1.00000000e+00],
       [3.10000000e+01, 1.50000000e+04, 3.17206578e-17],
       [3.60000000e+01, 1.44000000e+05, 1.00000000e+00],
       [1.80000000e+01, 6.80000000e+04, 3.17206578e-17],
       [4.70000000e+01, 4.30000000e+04, 1.00000000e+00],
       [3.00000000e+01, 4.90000000e+04, 1.00000000e+00],
       [2.80000000e+01, 5.50000000e+04, 3.17206578e-17],
       [3.70000000e+01, 5.50000000e+04, 1.00000000e+00],
       [3.90000000e+01, 7.70000000e+04, 1.00000000e+00],
       [2.00000000e+01, 8.60000000e+04, 1.00000000e+00],
       [3.20000000e+01, 1.17000000e+05, 3.17206578e-17],
       [3.70000000e+01, 7.70000000e+04, 1.00000000e+00],
       [1.90000000e+01, 8.50000

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],'penalty':['l1','l2']}

grid=GridSearchCV(LogisticRegression(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
#scoring w mention which metrics we need to get default value of scoring is For classifiers: usually accuracy and regressors: usually R² score
#we select the f1_weighted so it will give the high score value on this f1_weighted. we can select other metrics also

grid.fit(x_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


C:\Users\smani\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
10 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\smani\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\smani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\smani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueE

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l1', 'l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

### 5.Evaluation Metric

In [46]:
print(grid.best_params_)
#Using this we can see the best model atfer tuning
re=grid.cv_results_
#save the result and we can see this table method using pandas
#print(re)

{'penalty': 'l1', 'solver': 'liblinear'}


In [47]:
y_pred=grid.predict(x_test)

In [48]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
#0 correctly predict as not purchased and 79 wrongly predict as not purchased
#41 correctly predict as purchased and 0 wrongly predict as purchased 

[[ 0 79]
 [ 0 41]]


In [49]:
#print the classifier report
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        79
           1       0.34      1.00      0.51        41

    accuracy                           0.34       120
   macro avg       0.17      0.50      0.25       120
weighted avg       0.12      0.34      0.17       120



C:\Users\smani\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\smani\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\smani\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
#to see the specific vales in the confusion matrics, in average what ever we pass the metrics it will that value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'penalty': 'l1', 'solver': 'liblinear'}: 0.17401656314699793


⚖️ When to use what?
Scenario	Recommended average
Binary classification	'binary' (default if 2 classes)
Multiclass, balanced classes	'macro'
Multiclass, imbalanced classes	'weighted'
You want total accuracy-like score	'micro'
Multilabel classification	'samples' or 'micro'

In [51]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.002010  2.336015e-07         0.000000        0.000000            l1   
1       0.001608  8.040905e-04         0.000000        0.000000            l1   
2       0.009923  4.424244e-03         0.005982        0.001278            l1   
3       0.008349  1.398720e-03         0.004676        0.000907            l1   
4       0.008381  1.432922e-03         0.005173        0.000745            l2   
5       0.007752  1.844349e-03         0.005435        0.000805            l2   
6       0.005837  1.610452e-03         0.003222        0.000986            l2   
7       0.002820  9.859742e-04         0.002670        0.002556            l2   

  param_solver                                    params  split0_test_score  \
0    newton-cg  {'penalty': 'l1', 'solver': 'newton-cg'}                NaN   
1        lbfgs      {'penalty': 'l1', 'solver': 'lbfgs'}                NaN   
2    liblinear  {'penalty': 'l1', 'solver': 'liblinear'}           0.835985   
3         saga       {'penalty': 'l1', 'solver': 'saga'}           0.835985   
4    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.835985   
5        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.835985   
6    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.835985   
7         saga       {'penalty': 'l2', 'solver': 'saga'}           0.835985   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2           0.802399           0.644599           0.927778           0.909115   
3           0.802399           0.644599           0.927778           0.909115   
4           0.802399           0.644599           0.927778           0.890114   
5           0.802399           0.644599           0.927778           0.890114   
6           0.802399           0.644599           0.927778           0.890114   
7           0.802399           0.644599           0.927778           0.890114   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                7  
1              NaN             NaN                7  
2         0.823975        0.100806                1  
3         0.823975        0.100806                1  
4         0.820175        0.097839                3  
5         0.820175        0.097839                3  
6         0.820175        0.097839                3  
7         0.820175        0.097839                3

In [52]:
#roc and auc (Receiver Operating Characteristic) and (Area Under the Curve) are powerful tools for evaluating the performance of binary classification models.
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,-1])

0.5

In [53]:
# using this roc and auc for 2nd time verifiy the model and score
#score was very low so this algorithm not fit for this dataset

In [54]:
grid.predict([[46,41000,0]])

array([1], dtype=int64)