In [1]:
import pandas as ps
import numpy as np

### 1. Data collection

In [2]:
data_set=ps.read_csv("Social_Network_Ads.csv")

In [3]:
data_set

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
Data=ps.get_dummies(data_set,drop_first=True)

In [5]:
Data

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
Data=Data.drop("User ID", axis=1)
Data

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [7]:
Data["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

### 2.Split the input and output

In [8]:
independent=Data[["Age","EstimatedSalary","Gender_Male"]]
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [9]:
dependent=Data[["Purchased"]]
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

### 3.Split the train and test data

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
y_train

Purchased
92           0
223          1
234          0
232          1
377          0
..         ...
323          1
192          0
117          0
47           0
172          0

[280 rows x 1 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x_train=st.fit_transform(x_train)
x_test=st.transform(x_test)

In [13]:
x_train

array([[-1.1631724 , -1.5849703 ,  0.99288247],
       [ 2.17018137,  0.93098672,  0.99288247],
       [ 0.0133054 ,  1.22017719, -1.00716855],
       [ 0.20938504,  1.07558195,  0.99288247],
       [ 0.40546467, -0.48604654, -1.00716855],
       [-0.28081405, -0.31253226,  0.99288247],
       [ 0.99370357, -0.8330751 ,  0.99288247],
       [ 0.99370357,  1.8563962 , -1.00716855],
       [ 0.0133054 ,  1.24909623, -1.00716855],
       [-0.86905295,  2.26126285,  0.99288247],
       [-1.1631724 , -1.5849703 , -1.00716855],
       [ 2.17018137, -0.80415605,  0.99288247],
       [-1.35925203, -1.46929411,  0.99288247],
       [ 0.40546467,  2.2901819 ,  0.99288247],
       [ 0.79762394,  0.75747245, -1.00716855],
       [-0.96709276, -0.31253226,  0.99288247],
       [ 0.11134522,  0.75747245,  0.99288247],
       [-0.96709276,  0.55503912,  0.99288247],
       [ 0.30742485,  0.06341534,  0.99288247],
       [ 0.69958412, -1.26686079,  0.99288247],
       [-0.47689368, -0.0233418 , -1.007

### 4.Model crearion

In [14]:
from sklearn.svm import SVC

from sklearn.model_selection import GridSearchCV

param_grid ={'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000]}

grid=GridSearchCV(SVC(), param_grid, refit= True, verbose=3, n_jobs=-1, scoring="f1_weighted")

grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Users\smani\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [15]:
y_pred=grid.predict(x_test)

In [16]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [19]:
print(grid.best_params_)
#Using this we can see the best model atfer tuning
re=grid.cv_results_
#save the result and we can see this table method using pandas
#print(re)

{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}


### 5.Evaluation Metric

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [18]:
print(cm)

[[73  6]
 [ 4 37]]


In [20]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



In [23]:
#to see the specific vales in the confusion matrics, in average what ever we pass the metrics it will that value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9171245421245421


⚖️ When to use what?
Scenario	Recommended average
Binary classification	'binary' (default if 2 classes)
Multiclass, balanced classes	'macro'
Multiclass, imbalanced classes	'weighted'
You want total accuracy-like score	'micro'
Multilabel classification	'samples' or 'micro'

In [26]:
table=ps.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.016012      0.005344         0.005634        0.000809      10   
1        0.014074      0.007298         0.007341        0.002396      10   
2        0.009239      0.001450         0.005086        0.000990      10   
3        0.006137      0.000406         0.004549        0.001279      10   
4        0.007618      0.001410         0.006377        0.000700      10   
5        0.006728      0.001534         0.005573        0.000785      10   
6        0.008236      0.001192         0.005880        0.001756      10   
7        0.006446      0.000819         0.005629        0.000805      10   
8        0.016138      0.002434         0.005928        0.000126     100   
9        0.009545      0.002572         0.007079        0.002039     100   
10       0.021727      0.006647         0.005570        0.000785     100   
11       0.007769      0.001268         0.004823        0.001608     100   
12       0.019733      0.006756         0.005223        0.000984     100   
13       0.007073      0.001531         0.005720        0.000918     100   
14       0.017829      0.001742         0.005068        0.000972     100   
15       0.006930      0.003503         0.004769        0.000925     100   
16       0.097518      0.026734         0.004307        0.000732    1000   
17       0.013429      0.003186         0.005514        0.000761    1000   
18       0.106358      0.037778         0.004815        0.000796    1000   
19       0.007117      0.002420         0.004359        0.000835    1000   
20       0.108667      0.029131         0.005563        0.001420    1000   
21       0.016492      0.004905         0.004865        0.001079    1000   
22       0.132814      0.081905         0.004255        0.000884    1000   
23       0.004823      0.001028         0.003958        0.000104    1000   
24       0.165271      0.035703         0.003957        0.000104    2000   
25       0.021296      0.003376         0.005111        0.000903    2000   
26       0.200125      0.062305         0.004427        0.000970    2000   
27       0.003957      0.000104         0.004410        0.000803    2000   
28       0.171741      0.038828         0.004305        0.000731    2000   
29       0.020547      0.006610         0.004604        0.000946    2000   
30       0.196649      0.070708         0.005244        0.002603    2000   
31       0.006658      0.006822         0.004543        0.000765    2000   
32       0.343009      0.287662         0.001553        0.001904    3000   
33       0.016966      0.004783         0.005063        0.003853    3000   
34       0.241181      0.115781         0.003104        0.002007    3000   
35       0.007871      0.009056         0.004554        0.000941    3000   
36       0.315387      0.266773         0.003573        0.001111    3000   
37       0.020323      0.007273         0.001604        0.001965    3000   
38       0.271856      0.114550         0.001357        0.001514    3000   
39       0.004305      0.000730         0.003905        0.000128    3000   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto         poly   
3         auto      sigmoid   
4        scale       linear   
5        scale          rbf   
6        scale         poly   
7        scale      sigmoid   
8         auto       linear   
9         auto          rbf   
10        auto         poly   
11        auto      sigmoid   
12       scale       linear   
13       scale          rbf   
14       scale         poly   
15       scale      sigmoid   
16        auto       linear   
17        auto          rbf   
18        auto         poly   
19        auto      sigmoid   
20       scale       linear   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto       linear   
25        auto          rbf   
26        auto         poly   
27        auto     

In [27]:
#roc and auc (Receiver Operating Characteristic) and (Area Under the Curve) are powerful tools for evaluating the performance of binary classification models.
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,-1])

AttributeError: predict_proba is not available when  probability=False

In [28]:
grid.predict([[46,41000,0]])

array([1], dtype=int64)